version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  push_to_dockerhub_and_heroku:
    jobs:
      - docker/publish:
          image: karoliinaemilia/dockercircle
          tag: 'latest'
      - push_to_heroku
          requires:
            - docker/publish
jobs:
  push_to_heroku:
    machine: true
    working_directory: ~/devopsdockercircleci
    steps:
      - checkout
      - run:
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker pull karoliinaemilia/dockercircle
            docker tag registry.heroku.com/dockercircle/web karoliinaemilia/dockercircle
            docker push registry.heroku.com/dockercircle/web
            heroku container:release dockercircle  
