version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  push_to_dockerhub_and_heroku:
    jobs:
      - docker/publish:
          image: karoliinaemilia/dockercircle
          tag: 'latest'
      - push_to_heroku:
          requires:
            - docker/publish
jobs:
  push_to_heroku:
    machine: true
    working_directory: ~/devopsdockercircleci
    steps:
      - checkout
      - run:
          name: Login to docker
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run:
          name: Pull image and tag
          command: |
            docker pull karoliinaemilia/dockercircle
            docker tag karoliinaemilia/dockercircle registry.heroku.com/dockercircle/web
      - run:
          name: Push to heroku
          command: |
            heroku container:login
            docker push registry.heroku.com/dockercircle/web
            heroku container:release web -a=dockercircle  
