version: 2.1
jobs:
  build:
    docker:
      - image: karoliinaemilia/dockercircle
    steps:
      - checkout
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.1.0
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: karoliinaemilia/dockercircle
          tag: 'latest'
  heroku_deploy:
    requires:
      -deploy  
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build

