version: 2.1
jobs:
  build:
    docker:
      - image: karoliinaemilia/dockercircle
    steps:
      - checkout
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.1.0
workflows:
  heroku_deploy:
    jobs:
      - docker/publish:
          image: karoliinaemilia/dockercircle
          tag: 'latest'
      - build
          requires:
            -docker/publish
      - heroku/deploy-via-git:
          requires:
            - build

